# Generated by Django 3.2.4 on 2022-05-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
                ('gender', models.BooleanField(choices=[(True, '男'), (False, '女')], verbose_name='性別')),
                ('birth', models.DateTimeField(verbose_name='生日')),
            ],
            options={
                'verbose_name': '導演',
                'verbose_name_plural': '導演',
            },
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '分級',
                'verbose_name_plural': '分級',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '類型',
                'verbose_name_plural': '類型',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
                ('content', models.TextField(max_length=350, verbose_name='介紹')),
                ('playdate', models.DateTimeField(verbose_name='上映日')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director', verbose_name='導演')),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.rated', verbose_name='分級')),
                ('types', models.ManyToManyField(to='movies.Type', verbose_name='類型')),
            ],
            options={
                'verbose_name': '電影',
                'verbose_name_plural': '電影',
            },
        ),
    ]
